# -*- coding: utf-8 -*-
"""python (1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19gZTokH90nx7UXwCgNZ5V9WN_sNKZGg8
"""

1+2

327653+827386

a = True

type(a)

vish='7467'

vish

type(vish)

b=True

type(b)

b1=False

b1

c=5+6J

c

type(c)

a=2
b=2

a+b

a1,a2 =63,87

a1

a2

a1+a2

b="vish"

b

d=True

d

a,b,c,d = 4,"vish",6,True

d

b

type(b)

type(a)

type(d)

_a=456754

b1,b2 = True,False

b1-b2

b1*b2

b1/b2

#this is first pythone course
a=343

s1='vois'
a=654

s1+a

'vish'+'al'

a=5365

b=float(input())

b



d=input()

d

d=bool(input())

type(d)

e=float(input())

type(e)

e

s='vhsgvx'

s[2]

s[-4]

s1='pwskills'

s1[0:2]

s1[2:7]

s1[2:8]

s1[2:435]

s1[2:-6]

s1[0:4:7]

s1[0:-8]

s1[7:3:-1]

s1[-1:-5:-1]

s1[-1:-9:-1]

s1[::-1]

s1[0]

s1[0]='s'

